name: 'apkify'
author: 'Zack Siri'
description: 'builds project into alpine package'
inputs:
  repository:
    description: 'repository name'
    required: true
    default: ${{ github.repository }}
  version:
    description: 'version of the app'
    required: true
  build:
    description: 'build number'
    required: true
  depends:
    description: 'Runtime Dependencies'
    required: true
  makedepends:
    description: 'Build Dependencies'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --repository
    - ${{inputs.repository}}
    - --version
    - ${{inputs.version}}
    - --build
    - ${{inputs.build}}
    - --depends
    - ${{inputs.depends}}
    - --makedepends
    - ${{inputs.makedepends}}
