name: 'pakman'
author: 'Zack Siri'
description: 'builds project into alpine package'
inputs:
  command:
    description: 'command to run'
    required: true
  version:
    description: 'version'
  build:
    description: 'build'
  depends:
    description: 'dependencies'
  makedepends:
    description: 'build dependencies'
  archive:
    description: 'archive path'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --command
    - ${{inputs.command}}
    - --version
    - ${{inputs.version}}
    - --build
    - ${{inputs.build}}
    - --depends
    - ${{inputs.depends}}
    - --makedepends
    - ${{inputs.makedepends}}
    - --archive
    - ${{inputs.archive}}
