name: 'pakman'
author: 'Zack Siri'
description: 'builds project into alpine package'
inputs:
  command:
    description: 'command to run'
    required: true
  options:
    description: 'arguments'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --command
    - ${{inputs.command}}
    - --options
    - ${{inputs.options}}
