name: 'pakman'
author: 'Zack Siri'
description: 'builds project into alpine package'
inputs:
  stack:
    description: 'choose your alpine version'
    required: true
  command:
    description: 'command to run'
    required: true
  archive:
    description: 'archive path'
runs:
  using: 'docker'
  image: 'docker/${{inputs.stack}}'
  args:
    - --command
    - ${{inputs.command}}
    - --archive
    - ${{inputs.archive}}
branding:
  icon: 'package'
  color: 'purple'
