name: 'apkify'
author: 'Zack Siri'
description: 'builds project into alpine package'
inputs:
  repository:
    description: 'repository name'
    required: true
    default: ${{ github.repository }}
  version:
    description: 'version of the app'
    required: true
    default: echo "::set-env name=version::`git describe --tags --always`"
  build:
    description: 'build number'
    required: true
    default: echo "::set-env name=build::`git rev-list HEAD --count`"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --repository
    - ${{inputs.repository}}
    - --version
    - ${{inputs.version}}
    - --build
    - ${{inputs.build}}
