name: 'pakman'
author: 'Zack Siri'
description: 'builds project into alpine package'
inputs:
  alpine-version:
    description: 'alpine version'
    required: true
  command:
    description: 'command to run'
    required: true
  archive:
    description: 'archive path'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.alpine-version}}
    - --command
    - ${{inputs.command}}
    - --archive
    - ${{inputs.archive}}
branding:
  icon: 'package'
  color: 'purple'
