name: 'apkify'
author: 'Zack Siri'
description: 'builds project into alpine package'
inputs:
  version:
    description: 'version of the app'
    required: true
  build:
    description: 'build number'
    required: true
  depends:
    description: 'Runtime Dependencies'
    required: true
  makedepends:
    description: 'Build Dependencies'
    required: true
  runtime_vars:
    description: 'Runtime Variables'
    required: true
    default: 'DATABASE_URL'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --version
    - ${{inputs.version}}
    - --build
    - ${{inputs.build}}
    - --depends
    - ${{inputs.depends}}
    - --makedepends
    - ${{inputs.makedepends}}
    - --runtime_vars
    - ${{inputs.runtime_vars}}
